export const CREATE = 'CREATE';
export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_POST_BY_ID = 'FETCH_POST_BY_ID';
export const FETCH_ALL_BY_SEARCH = 'FETCH_ALL_BY_SEARCH';
export const FETCH_RECOMMENDED_POSTS = 'FETCH_RECOMMENDED_POSTS';
export const LIKE = 'LIKE';
export const DELETE = 'DELETE';
export const UPDATE = 'UPDATE';
export const COMMENT_ON_POST = 'COMMENT_ON_POST';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const START_LOADING_RECOMMENDED_POSTS = 'START_LOADING_RECOMMENDED_POSTS';
export const END_LOADING_RECOMMENDED_POSTS = 'END_LOADING_RECOMMENDED_POSTS';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const FETCH_ALL_CHAPTERS = 'FETCH_ALL_CHAPTERS';
export const START_LOADING_CHAPTERS = 'START_LOADING_CHAPTERS';
export const END_LOADING_CHAPTERS = 'END_LOADING_CHAPTERS';
export const CREATE_CHAPTER = 'CREATE_CHAPTER';

export const FETCH_ALL_BOOKS = 'FETCH_ALL_BOOKS';
export const START_LOADING_BOOKS = 'START_LOADING_BOOKS';
export const END_LOADING_BOOKS = 'END_LOADING_BOOKS';
export const CREATE_BOOK = 'CREATE_BOOK';
